// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: dedup.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ── Group A: GetItem ─────────────────────────────────────────────────────────
// Same structure every time – scalars, a map, a repeated field, and 2 levels
// of nested messages.  Calling with id=1,2,3 should all hash identically.
type GetItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemReq) Reset() {
	*x = GetItemReq{}
	mi := &file_dedup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemReq) ProtoMessage() {}

func (x *GetItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_dedup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemReq.ProtoReflect.Descriptor instead.
func (*GetItemReq) Descriptor() ([]byte, []int) {
	return file_dedup_proto_rawDescGZIP(), []int{0}
}

func (x *GetItemReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	InStock       bool                   `protobuf:"varint,4,opt,name=in_stock,json=inStock,proto3" json:"in_stock,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Detail        *ItemDetail            `protobuf:"bytes,7,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_dedup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_dedup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_dedup_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Item) GetInStock() bool {
	if x != nil {
		return x.InStock
	}
	return false
}

func (x *Item) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Item) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Item) GetDetail() *ItemDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type ItemDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	StockCount    int32                  `protobuf:"varint,2,opt,name=stock_count,json=stockCount,proto3" json:"stock_count,omitempty"`
	Supplier      *Supplier              `protobuf:"bytes,3,opt,name=supplier,proto3" json:"supplier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemDetail) Reset() {
	*x = ItemDetail{}
	mi := &file_dedup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemDetail) ProtoMessage() {}

func (x *ItemDetail) ProtoReflect() protoreflect.Message {
	mi := &file_dedup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemDetail.ProtoReflect.Descriptor instead.
func (*ItemDetail) Descriptor() ([]byte, []int) {
	return file_dedup_proto_rawDescGZIP(), []int{2}
}

func (x *ItemDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ItemDetail) GetStockCount() int32 {
	if x != nil {
		return x.StockCount
	}
	return 0
}

func (x *ItemDetail) GetSupplier() *Supplier {
	if x != nil {
		return x.Supplier
	}
	return nil
}

type Supplier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Contact       string                 `protobuf:"bytes,3,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Supplier) Reset() {
	*x = Supplier{}
	mi := &file_dedup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Supplier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Supplier) ProtoMessage() {}

func (x *Supplier) ProtoReflect() protoreflect.Message {
	mi := &file_dedup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Supplier.ProtoReflect.Descriptor instead.
func (*Supplier) Descriptor() ([]byte, []int) {
	return file_dedup_proto_rawDescGZIP(), []int{3}
}

func (x *Supplier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Supplier) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Supplier) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

// ── Group B: GetWidget ───────────────────────────────────────────────────────
// mode="full"    → Widget.config is populated (field 3 present in wire)
// mode="minimal" → Widget.config is nil        (field 3 absent in wire)
// Different structural hashes → 2 TCs.
type GetWidgetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWidgetReq) Reset() {
	*x = GetWidgetReq{}
	mi := &file_dedup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWidgetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWidgetReq) ProtoMessage() {}

func (x *GetWidgetReq) ProtoReflect() protoreflect.Message {
	mi := &file_dedup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWidgetReq.ProtoReflect.Descriptor instead.
func (*GetWidgetReq) Descriptor() ([]byte, []int) {
	return file_dedup_proto_rawDescGZIP(), []int{4}
}

func (x *GetWidgetReq) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type Widget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Config        *WidgetConfig          `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"` // absent in minimal mode
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Widget) Reset() {
	*x = Widget{}
	mi := &file_dedup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Widget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Widget) ProtoMessage() {}

func (x *Widget) ProtoReflect() protoreflect.Message {
	mi := &file_dedup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Widget.ProtoReflect.Descriptor instead.
func (*Widget) Descriptor() ([]byte, []int) {
	return file_dedup_proto_rawDescGZIP(), []int{5}
}

func (x *Widget) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Widget) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Widget) GetConfig() *WidgetConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type WidgetConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Theme         string                 `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Style         *WidgetStyle           `protobuf:"bytes,3,opt,name=style,proto3" json:"style,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WidgetConfig) Reset() {
	*x = WidgetConfig{}
	mi := &file_dedup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetConfig) ProtoMessage() {}

func (x *WidgetConfig) ProtoReflect() protoreflect.Message {
	mi := &file_dedup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetConfig.ProtoReflect.Descriptor instead.
func (*WidgetConfig) Descriptor() ([]byte, []int) {
	return file_dedup_proto_rawDescGZIP(), []int{6}
}

func (x *WidgetConfig) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *WidgetConfig) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *WidgetConfig) GetStyle() *WidgetStyle {
	if x != nil {
		return x.Style
	}
	return nil
}

type WidgetStyle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Color         string                 `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	Bold          bool                   `protobuf:"varint,2,opt,name=bold,proto3" json:"bold,omitempty"`
	Weight        int32                  `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WidgetStyle) Reset() {
	*x = WidgetStyle{}
	mi := &file_dedup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetStyle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetStyle) ProtoMessage() {}

func (x *WidgetStyle) ProtoReflect() protoreflect.Message {
	mi := &file_dedup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetStyle.ProtoReflect.Descriptor instead.
func (*WidgetStyle) Descriptor() ([]byte, []int) {
	return file_dedup_proto_rawDescGZIP(), []int{7}
}

func (x *WidgetStyle) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *WidgetStyle) GetBold() bool {
	if x != nil {
		return x.Bold
	}
	return false
}

func (x *WidgetStyle) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

// ── Group C: RiskyCall ───────────────────────────────────────────────────────
// should_fail=false → grpc-status trailer = "0"
// should_fail=true  → grpc-status trailer = "3" (InvalidArgument)
// The schema key includes grpc-status → 2 distinct TCs.
type RiskyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShouldFail    bool                   `protobuf:"varint,1,opt,name=should_fail,json=shouldFail,proto3" json:"should_fail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskyReq) Reset() {
	*x = RiskyReq{}
	mi := &file_dedup_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskyReq) ProtoMessage() {}

func (x *RiskyReq) ProtoReflect() protoreflect.Message {
	mi := &file_dedup_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskyReq.ProtoReflect.Descriptor instead.
func (*RiskyReq) Descriptor() ([]byte, []int) {
	return file_dedup_proto_rawDescGZIP(), []int{8}
}

func (x *RiskyReq) GetShouldFail() bool {
	if x != nil {
		return x.ShouldFail
	}
	return false
}

type RiskyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskyResp) Reset() {
	*x = RiskyResp{}
	mi := &file_dedup_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskyResp) ProtoMessage() {}

func (x *RiskyResp) ProtoReflect() protoreflect.Message {
	mi := &file_dedup_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskyResp.ProtoReflect.Descriptor instead.
func (*RiskyResp) Descriptor() ([]byte, []int) {
	return file_dedup_proto_rawDescGZIP(), []int{9}
}

func (x *RiskyResp) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// ── Group D: GetReport ───────────────────────────────────────────────────────
// Deeply nested: Report → ReportSummary → ReportMeta → Environment (with map)
//
//	Report → repeated Section → repeated Row
//
// Calling with period="Q1","Q2","Q3" all produce the same structure → 1 TC.
type ReportReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportReq) Reset() {
	*x = ReportReq{}
	mi := &file_dedup_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportReq) ProtoMessage() {}

func (x *ReportReq) ProtoReflect() protoreflect.Message {
	mi := &file_dedup_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportReq.ProtoReflect.Descriptor instead.
func (*ReportReq) Descriptor() ([]byte, []int) {
	return file_dedup_proto_rawDescGZIP(), []int{10}
}

func (x *ReportReq) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type Report struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	Summary       *ReportSummary         `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Sections      []*Section             `protobuf:"bytes,4,rep,name=sections,proto3" json:"sections,omitempty"`
	Counters      map[string]int32       `protobuf:"bytes,5,rep,name=counters,proto3" json:"counters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_dedup_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_dedup_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_dedup_proto_rawDescGZIP(), []int{11}
}

func (x *Report) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Report) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *Report) GetSummary() *ReportSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *Report) GetSections() []*Section {
	if x != nil {
		return x.Sections
	}
	return nil
}

func (x *Report) GetCounters() map[string]int32 {
	if x != nil {
		return x.Counters
	}
	return nil
}

type ReportSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Passed        int32                  `protobuf:"varint,2,opt,name=passed,proto3" json:"passed,omitempty"`
	Failed        int32                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	Meta          *ReportMeta            `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportSummary) Reset() {
	*x = ReportSummary{}
	mi := &file_dedup_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSummary) ProtoMessage() {}

func (x *ReportSummary) ProtoReflect() protoreflect.Message {
	mi := &file_dedup_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSummary.ProtoReflect.Descriptor instead.
func (*ReportSummary) Descriptor() ([]byte, []int) {
	return file_dedup_proto_rawDescGZIP(), []int{12}
}

func (x *ReportSummary) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ReportSummary) GetPassed() int32 {
	if x != nil {
		return x.Passed
	}
	return 0
}

func (x *ReportSummary) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *ReportSummary) GetMeta() *ReportMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ReportMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GeneratedBy   string                 `protobuf:"bytes,1,opt,name=generated_by,json=generatedBy,proto3" json:"generated_by,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Env           *Environment           `protobuf:"bytes,3,opt,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportMeta) Reset() {
	*x = ReportMeta{}
	mi := &file_dedup_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportMeta) ProtoMessage() {}

func (x *ReportMeta) ProtoReflect() protoreflect.Message {
	mi := &file_dedup_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportMeta.ProtoReflect.Descriptor instead.
func (*ReportMeta) Descriptor() ([]byte, []int) {
	return file_dedup_proto_rawDescGZIP(), []int{13}
}

func (x *ReportMeta) GetGeneratedBy() string {
	if x != nil {
		return x.GeneratedBy
	}
	return ""
}

func (x *ReportMeta) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ReportMeta) GetEnv() *Environment {
	if x != nil {
		return x.Env
	}
	return nil
}

type Environment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Environment) Reset() {
	*x = Environment{}
	mi := &file_dedup_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Environment) ProtoMessage() {}

func (x *Environment) ProtoReflect() protoreflect.Message {
	mi := &file_dedup_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Environment.ProtoReflect.Descriptor instead.
func (*Environment) Descriptor() ([]byte, []int) {
	return file_dedup_proto_rawDescGZIP(), []int{14}
}

func (x *Environment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Environment) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Environment) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Section struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Section) Reset() {
	*x = Section{}
	mi := &file_dedup_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Section) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Section) ProtoMessage() {}

func (x *Section) ProtoReflect() protoreflect.Message {
	mi := &file_dedup_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Section.ProtoReflect.Descriptor instead.
func (*Section) Descriptor() ([]byte, []int) {
	return file_dedup_proto_rawDescGZIP(), []int{15}
}

func (x *Section) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Section) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_dedup_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_dedup_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_dedup_proto_rawDescGZIP(), []int{16}
}

func (x *Row) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Row) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Row) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// ── Group E: GetVariant ──────────────────────────────────────────────────────
// oneof puts different field numbers on the wire depending on which branch is
// set.  type="text" → field 1, type="number" → field 2, type="flag" → field 3.
// Three distinct structural hashes → 3 TCs.
type VariantReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariantReq) Reset() {
	*x = VariantReq{}
	mi := &file_dedup_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariantReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariantReq) ProtoMessage() {}

func (x *VariantReq) ProtoReflect() protoreflect.Message {
	mi := &file_dedup_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariantReq.ProtoReflect.Descriptor instead.
func (*VariantReq) Descriptor() ([]byte, []int) {
	return file_dedup_proto_rawDescGZIP(), []int{17}
}

func (x *VariantReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type VariantResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*VariantResp_TextValue
	//	*VariantResp_NumberValue
	//	*VariantResp_FlagValue
	Payload       isVariantResp_Payload `protobuf_oneof:"payload"`
	Label         string                `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariantResp) Reset() {
	*x = VariantResp{}
	mi := &file_dedup_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariantResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariantResp) ProtoMessage() {}

func (x *VariantResp) ProtoReflect() protoreflect.Message {
	mi := &file_dedup_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariantResp.ProtoReflect.Descriptor instead.
func (*VariantResp) Descriptor() ([]byte, []int) {
	return file_dedup_proto_rawDescGZIP(), []int{18}
}

func (x *VariantResp) GetPayload() isVariantResp_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *VariantResp) GetTextValue() string {
	if x != nil {
		if x, ok := x.Payload.(*VariantResp_TextValue); ok {
			return x.TextValue
		}
	}
	return ""
}

func (x *VariantResp) GetNumberValue() int32 {
	if x != nil {
		if x, ok := x.Payload.(*VariantResp_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *VariantResp) GetFlagValue() bool {
	if x != nil {
		if x, ok := x.Payload.(*VariantResp_FlagValue); ok {
			return x.FlagValue
		}
	}
	return false
}

func (x *VariantResp) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type isVariantResp_Payload interface {
	isVariantResp_Payload()
}

type VariantResp_TextValue struct {
	TextValue string `protobuf:"bytes,1,opt,name=text_value,json=textValue,proto3,oneof"`
}

type VariantResp_NumberValue struct {
	NumberValue int32 `protobuf:"varint,2,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type VariantResp_FlagValue struct {
	FlagValue bool `protobuf:"varint,3,opt,name=flag_value,json=flagValue,proto3,oneof"`
}

func (*VariantResp_TextValue) isVariantResp_Payload() {}

func (*VariantResp_NumberValue) isVariantResp_Payload() {}

func (*VariantResp_FlagValue) isVariantResp_Payload() {}

// ── Group F: ListItems ───────────────────────────────────────────────────────
// include_items=true  → items repeated field is populated (field 1 on wire)
// include_items=false → items is empty so field 1 is absent from wire
// Different structural hashes → 2 TCs.
type ListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncludeItems  bool                   `protobuf:"varint,1,opt,name=include_items,json=includeItems,proto3" json:"include_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReq) Reset() {
	*x = ListReq{}
	mi := &file_dedup_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReq) ProtoMessage() {}

func (x *ListReq) ProtoReflect() protoreflect.Message {
	mi := &file_dedup_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReq.ProtoReflect.Descriptor instead.
func (*ListReq) Descriptor() ([]byte, []int) {
	return file_dedup_proto_rawDescGZIP(), []int{19}
}

func (x *ListReq) GetIncludeItems() bool {
	if x != nil {
		return x.IncludeItems
	}
	return false
}

type ListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ListItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResp) Reset() {
	*x = ListResp{}
	mi := &file_dedup_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResp) ProtoMessage() {}

func (x *ListResp) ProtoReflect() protoreflect.Message {
	mi := &file_dedup_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResp.ProtoReflect.Descriptor instead.
func (*ListResp) Descriptor() ([]byte, []int) {
	return file_dedup_proto_rawDescGZIP(), []int{20}
}

func (x *ListResp) GetItems() []*ListItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItem) Reset() {
	*x = ListItem{}
	mi := &file_dedup_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItem) ProtoMessage() {}

func (x *ListItem) ProtoReflect() protoreflect.Message {
	mi := &file_dedup_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItem.ProtoReflect.Descriptor instead.
func (*ListItem) Descriptor() ([]byte, []int) {
	return file_dedup_proto_rawDescGZIP(), []int{21}
}

func (x *ListItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListItem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

var File_dedup_proto protoreflect.FileDescriptor

const file_dedup_proto_rawDesc = "" +
	"\n" +
	"\vdedup.proto\x12\tdeduptest\"\x1c\n" +
	"\n" +
	"GetItemReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x9e\x02\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x19\n" +
	"\bin_stock\x18\x04 \x01(\bR\ainStock\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12?\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2\x1f.deduptest.Item.AttributesEntryR\n" +
	"attributes\x12-\n" +
	"\x06detail\x18\a \x01(\v2\x15.deduptest.ItemDetailR\x06detail\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x80\x01\n" +
	"\n" +
	"ItemDetail\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x1f\n" +
	"\vstock_count\x18\x02 \x01(\x05R\n" +
	"stockCount\x12/\n" +
	"\bsupplier\x18\x03 \x01(\v2\x13.deduptest.SupplierR\bsupplier\"R\n" +
	"\bSupplier\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x18\n" +
	"\acontact\x18\x03 \x01(\tR\acontact\"\"\n" +
	"\fGetWidgetReq\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\"]\n" +
	"\x06Widget\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.deduptest.WidgetConfigR\x06config\"f\n" +
	"\fWidgetConfig\x12\x14\n" +
	"\x05theme\x18\x01 \x01(\tR\x05theme\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12,\n" +
	"\x05style\x18\x03 \x01(\v2\x16.deduptest.WidgetStyleR\x05style\"O\n" +
	"\vWidgetStyle\x12\x14\n" +
	"\x05color\x18\x01 \x01(\tR\x05color\x12\x12\n" +
	"\x04bold\x18\x02 \x01(\bR\x04bold\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x05R\x06weight\"+\n" +
	"\bRiskyReq\x12\x1f\n" +
	"\vshould_fail\x18\x01 \x01(\bR\n" +
	"shouldFail\"#\n" +
	"\tRiskyResp\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"#\n" +
	"\tReportReq\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\"\x8e\x02\n" +
	"\x06Report\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\x122\n" +
	"\asummary\x18\x03 \x01(\v2\x18.deduptest.ReportSummaryR\asummary\x12.\n" +
	"\bsections\x18\x04 \x03(\v2\x12.deduptest.SectionR\bsections\x12;\n" +
	"\bcounters\x18\x05 \x03(\v2\x1f.deduptest.Report.CountersEntryR\bcounters\x1a;\n" +
	"\rCountersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x80\x01\n" +
	"\rReportSummary\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x16\n" +
	"\x06passed\x18\x02 \x01(\x05R\x06passed\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\x12)\n" +
	"\x04meta\x18\x04 \x01(\v2\x15.deduptest.ReportMetaR\x04meta\"s\n" +
	"\n" +
	"ReportMeta\x12!\n" +
	"\fgenerated_by\x18\x01 \x01(\tR\vgeneratedBy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12(\n" +
	"\x03env\x18\x03 \x01(\v2\x16.deduptest.EnvironmentR\x03env\"\xb0\x01\n" +
	"\vEnvironment\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12:\n" +
	"\x06labels\x18\x03 \x03(\v2\".deduptest.Environment.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\aSection\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\"\n" +
	"\x04rows\x18\x02 \x03(\v2\x0e.deduptest.RowR\x04rows\"C\n" +
	"\x03Row\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\" \n" +
	"\n" +
	"VariantReq\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"\x95\x01\n" +
	"\vVariantResp\x12\x1f\n" +
	"\n" +
	"text_value\x18\x01 \x01(\tH\x00R\ttextValue\x12#\n" +
	"\fnumber_value\x18\x02 \x01(\x05H\x00R\vnumberValue\x12\x1f\n" +
	"\n" +
	"flag_value\x18\x03 \x01(\bH\x00R\tflagValue\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05labelB\t\n" +
	"\apayload\".\n" +
	"\aListReq\x12#\n" +
	"\rinclude_items\x18\x01 \x01(\bR\fincludeItems\"K\n" +
	"\bListResp\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.deduptest.ListItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"B\n" +
	"\bListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind2\xdb\x02\n" +
	"\fDedupService\x121\n" +
	"\aGetItem\x12\x15.deduptest.GetItemReq\x1a\x0f.deduptest.Item\x127\n" +
	"\tGetWidget\x12\x17.deduptest.GetWidgetReq\x1a\x11.deduptest.Widget\x126\n" +
	"\tRiskyCall\x12\x13.deduptest.RiskyReq\x1a\x14.deduptest.RiskyResp\x124\n" +
	"\tGetReport\x12\x14.deduptest.ReportReq\x1a\x11.deduptest.Report\x12;\n" +
	"\n" +
	"GetVariant\x12\x15.deduptest.VariantReq\x1a\x16.deduptest.VariantResp\x124\n" +
	"\tListItems\x12\x12.deduptest.ListReq\x1a\x13.deduptest.ListRespB\x06Z\x04./pbb\x06proto3"

var (
	file_dedup_proto_rawDescOnce sync.Once
	file_dedup_proto_rawDescData []byte
)

func file_dedup_proto_rawDescGZIP() []byte {
	file_dedup_proto_rawDescOnce.Do(func() {
		file_dedup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dedup_proto_rawDesc), len(file_dedup_proto_rawDesc)))
	})
	return file_dedup_proto_rawDescData
}

var file_dedup_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_dedup_proto_goTypes = []any{
	(*GetItemReq)(nil),    // 0: deduptest.GetItemReq
	(*Item)(nil),          // 1: deduptest.Item
	(*ItemDetail)(nil),    // 2: deduptest.ItemDetail
	(*Supplier)(nil),      // 3: deduptest.Supplier
	(*GetWidgetReq)(nil),  // 4: deduptest.GetWidgetReq
	(*Widget)(nil),        // 5: deduptest.Widget
	(*WidgetConfig)(nil),  // 6: deduptest.WidgetConfig
	(*WidgetStyle)(nil),   // 7: deduptest.WidgetStyle
	(*RiskyReq)(nil),      // 8: deduptest.RiskyReq
	(*RiskyResp)(nil),     // 9: deduptest.RiskyResp
	(*ReportReq)(nil),     // 10: deduptest.ReportReq
	(*Report)(nil),        // 11: deduptest.Report
	(*ReportSummary)(nil), // 12: deduptest.ReportSummary
	(*ReportMeta)(nil),    // 13: deduptest.ReportMeta
	(*Environment)(nil),   // 14: deduptest.Environment
	(*Section)(nil),       // 15: deduptest.Section
	(*Row)(nil),           // 16: deduptest.Row
	(*VariantReq)(nil),    // 17: deduptest.VariantReq
	(*VariantResp)(nil),   // 18: deduptest.VariantResp
	(*ListReq)(nil),       // 19: deduptest.ListReq
	(*ListResp)(nil),      // 20: deduptest.ListResp
	(*ListItem)(nil),      // 21: deduptest.ListItem
	nil,                   // 22: deduptest.Item.AttributesEntry
	nil,                   // 23: deduptest.Report.CountersEntry
	nil,                   // 24: deduptest.Environment.LabelsEntry
}
var file_dedup_proto_depIdxs = []int32{
	22, // 0: deduptest.Item.attributes:type_name -> deduptest.Item.AttributesEntry
	2,  // 1: deduptest.Item.detail:type_name -> deduptest.ItemDetail
	3,  // 2: deduptest.ItemDetail.supplier:type_name -> deduptest.Supplier
	6,  // 3: deduptest.Widget.config:type_name -> deduptest.WidgetConfig
	7,  // 4: deduptest.WidgetConfig.style:type_name -> deduptest.WidgetStyle
	12, // 5: deduptest.Report.summary:type_name -> deduptest.ReportSummary
	15, // 6: deduptest.Report.sections:type_name -> deduptest.Section
	23, // 7: deduptest.Report.counters:type_name -> deduptest.Report.CountersEntry
	13, // 8: deduptest.ReportSummary.meta:type_name -> deduptest.ReportMeta
	14, // 9: deduptest.ReportMeta.env:type_name -> deduptest.Environment
	24, // 10: deduptest.Environment.labels:type_name -> deduptest.Environment.LabelsEntry
	16, // 11: deduptest.Section.rows:type_name -> deduptest.Row
	21, // 12: deduptest.ListResp.items:type_name -> deduptest.ListItem
	0,  // 13: deduptest.DedupService.GetItem:input_type -> deduptest.GetItemReq
	4,  // 14: deduptest.DedupService.GetWidget:input_type -> deduptest.GetWidgetReq
	8,  // 15: deduptest.DedupService.RiskyCall:input_type -> deduptest.RiskyReq
	10, // 16: deduptest.DedupService.GetReport:input_type -> deduptest.ReportReq
	17, // 17: deduptest.DedupService.GetVariant:input_type -> deduptest.VariantReq
	19, // 18: deduptest.DedupService.ListItems:input_type -> deduptest.ListReq
	1,  // 19: deduptest.DedupService.GetItem:output_type -> deduptest.Item
	5,  // 20: deduptest.DedupService.GetWidget:output_type -> deduptest.Widget
	9,  // 21: deduptest.DedupService.RiskyCall:output_type -> deduptest.RiskyResp
	11, // 22: deduptest.DedupService.GetReport:output_type -> deduptest.Report
	18, // 23: deduptest.DedupService.GetVariant:output_type -> deduptest.VariantResp
	20, // 24: deduptest.DedupService.ListItems:output_type -> deduptest.ListResp
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_dedup_proto_init() }
func file_dedup_proto_init() {
	if File_dedup_proto != nil {
		return
	}
	file_dedup_proto_msgTypes[18].OneofWrappers = []any{
		(*VariantResp_TextValue)(nil),
		(*VariantResp_NumberValue)(nil),
		(*VariantResp_FlagValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dedup_proto_rawDesc), len(file_dedup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dedup_proto_goTypes,
		DependencyIndexes: file_dedup_proto_depIdxs,
		MessageInfos:      file_dedup_proto_msgTypes,
	}.Build()
	File_dedup_proto = out.File
	file_dedup_proto_goTypes = nil
	file_dedup_proto_depIdxs = nil
}
