// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.2
// source: dedup.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DedupService_GetItem_FullMethodName    = "/deduptest.DedupService/GetItem"
	DedupService_GetWidget_FullMethodName  = "/deduptest.DedupService/GetWidget"
	DedupService_RiskyCall_FullMethodName  = "/deduptest.DedupService/RiskyCall"
	DedupService_GetReport_FullMethodName  = "/deduptest.DedupService/GetReport"
	DedupService_GetVariant_FullMethodName = "/deduptest.DedupService/GetVariant"
	DedupService_ListItems_FullMethodName  = "/deduptest.DedupService/ListItems"
)

// DedupServiceClient is the client API for DedupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DedupService exercises every static-dedup edge case:
//
//	GetItem      – same structure, different scalar values       → all dedup to 1
//	GetWidget    – optional nested field absent vs present        → 2 distinct TCs
//	RiskyCall    – success (grpc-status=0) vs error (status=3)   → 2 distinct TCs
//	GetReport    – deeply nested + maps + repeated               → dedup to 1
//	GetVariant   – oneof: three field-number variants            → 3 distinct TCs
//	ListItems    – non-empty repeated vs empty (field absent)    → 2 distinct TCs
type DedupServiceClient interface {
	GetItem(ctx context.Context, in *GetItemReq, opts ...grpc.CallOption) (*Item, error)
	GetWidget(ctx context.Context, in *GetWidgetReq, opts ...grpc.CallOption) (*Widget, error)
	RiskyCall(ctx context.Context, in *RiskyReq, opts ...grpc.CallOption) (*RiskyResp, error)
	GetReport(ctx context.Context, in *ReportReq, opts ...grpc.CallOption) (*Report, error)
	GetVariant(ctx context.Context, in *VariantReq, opts ...grpc.CallOption) (*VariantResp, error)
	ListItems(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListResp, error)
}

type dedupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDedupServiceClient(cc grpc.ClientConnInterface) DedupServiceClient {
	return &dedupServiceClient{cc}
}

func (c *dedupServiceClient) GetItem(ctx context.Context, in *GetItemReq, opts ...grpc.CallOption) (*Item, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Item)
	err := c.cc.Invoke(ctx, DedupService_GetItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dedupServiceClient) GetWidget(ctx context.Context, in *GetWidgetReq, opts ...grpc.CallOption) (*Widget, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Widget)
	err := c.cc.Invoke(ctx, DedupService_GetWidget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dedupServiceClient) RiskyCall(ctx context.Context, in *RiskyReq, opts ...grpc.CallOption) (*RiskyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiskyResp)
	err := c.cc.Invoke(ctx, DedupService_RiskyCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dedupServiceClient) GetReport(ctx context.Context, in *ReportReq, opts ...grpc.CallOption) (*Report, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Report)
	err := c.cc.Invoke(ctx, DedupService_GetReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dedupServiceClient) GetVariant(ctx context.Context, in *VariantReq, opts ...grpc.CallOption) (*VariantResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VariantResp)
	err := c.cc.Invoke(ctx, DedupService_GetVariant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dedupServiceClient) ListItems(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResp)
	err := c.cc.Invoke(ctx, DedupService_ListItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DedupServiceServer is the server API for DedupService service.
// All implementations must embed UnimplementedDedupServiceServer
// for forward compatibility.
//
// DedupService exercises every static-dedup edge case:
//
//	GetItem      – same structure, different scalar values       → all dedup to 1
//	GetWidget    – optional nested field absent vs present        → 2 distinct TCs
//	RiskyCall    – success (grpc-status=0) vs error (status=3)   → 2 distinct TCs
//	GetReport    – deeply nested + maps + repeated               → dedup to 1
//	GetVariant   – oneof: three field-number variants            → 3 distinct TCs
//	ListItems    – non-empty repeated vs empty (field absent)    → 2 distinct TCs
type DedupServiceServer interface {
	GetItem(context.Context, *GetItemReq) (*Item, error)
	GetWidget(context.Context, *GetWidgetReq) (*Widget, error)
	RiskyCall(context.Context, *RiskyReq) (*RiskyResp, error)
	GetReport(context.Context, *ReportReq) (*Report, error)
	GetVariant(context.Context, *VariantReq) (*VariantResp, error)
	ListItems(context.Context, *ListReq) (*ListResp, error)
	mustEmbedUnimplementedDedupServiceServer()
}

// UnimplementedDedupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDedupServiceServer struct{}

func (UnimplementedDedupServiceServer) GetItem(context.Context, *GetItemReq) (*Item, error) {
	return nil, status.Error(codes.Unimplemented, "method GetItem not implemented")
}
func (UnimplementedDedupServiceServer) GetWidget(context.Context, *GetWidgetReq) (*Widget, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWidget not implemented")
}
func (UnimplementedDedupServiceServer) RiskyCall(context.Context, *RiskyReq) (*RiskyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RiskyCall not implemented")
}
func (UnimplementedDedupServiceServer) GetReport(context.Context, *ReportReq) (*Report, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReport not implemented")
}
func (UnimplementedDedupServiceServer) GetVariant(context.Context, *VariantReq) (*VariantResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVariant not implemented")
}
func (UnimplementedDedupServiceServer) ListItems(context.Context, *ListReq) (*ListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListItems not implemented")
}
func (UnimplementedDedupServiceServer) mustEmbedUnimplementedDedupServiceServer() {}
func (UnimplementedDedupServiceServer) testEmbeddedByValue()                      {}

// UnsafeDedupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DedupServiceServer will
// result in compilation errors.
type UnsafeDedupServiceServer interface {
	mustEmbedUnimplementedDedupServiceServer()
}

func RegisterDedupServiceServer(s grpc.ServiceRegistrar, srv DedupServiceServer) {
	// If the following call panics, it indicates UnimplementedDedupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DedupService_ServiceDesc, srv)
}

func _DedupService_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DedupServiceServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DedupService_GetItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DedupServiceServer).GetItem(ctx, req.(*GetItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DedupService_GetWidget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWidgetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DedupServiceServer).GetWidget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DedupService_GetWidget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DedupServiceServer).GetWidget(ctx, req.(*GetWidgetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DedupService_RiskyCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiskyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DedupServiceServer).RiskyCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DedupService_RiskyCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DedupServiceServer).RiskyCall(ctx, req.(*RiskyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DedupService_GetReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DedupServiceServer).GetReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DedupService_GetReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DedupServiceServer).GetReport(ctx, req.(*ReportReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DedupService_GetVariant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VariantReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DedupServiceServer).GetVariant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DedupService_GetVariant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DedupServiceServer).GetVariant(ctx, req.(*VariantReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DedupService_ListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DedupServiceServer).ListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DedupService_ListItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DedupServiceServer).ListItems(ctx, req.(*ListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DedupService_ServiceDesc is the grpc.ServiceDesc for DedupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DedupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deduptest.DedupService",
	HandlerType: (*DedupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetItem",
			Handler:    _DedupService_GetItem_Handler,
		},
		{
			MethodName: "GetWidget",
			Handler:    _DedupService_GetWidget_Handler,
		},
		{
			MethodName: "RiskyCall",
			Handler:    _DedupService_RiskyCall_Handler,
		},
		{
			MethodName: "GetReport",
			Handler:    _DedupService_GetReport_Handler,
		},
		{
			MethodName: "GetVariant",
			Handler:    _DedupService_GetVariant_Handler,
		},
		{
			MethodName: "ListItems",
			Handler:    _DedupService_ListItems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dedup.proto",
}
